README.md, cmd/configure.go, cmd/process.go, cmd/serve.go, go.mod, go.sum, utils/config/env.go, utils/config/env_test.go
Enhancement
___
- Introduced the ability to encrypt the `.env` file to protect API keys and other sensitive information.
- Added a new command-line flag `--encrypt` to encrypt configuration files.
- Implemented AES-256-GCM encryption with password-derived keys for secure configuration storage.
- Updated commands to handle encrypted configurations by prompting for passwords.
- Added tests for encryption and decryption functionalities.
- Updated documentation to include instructions on using the new encryption feature.
___
- `cmd/configure.go`: Added an `encryptFlag` to handle encryption of configuration files. Implemented logic to prompt for a password and confirm it before encrypting the configuration file. Updated configuration loading to handle …
=> feat: encrypted env

README.md, cmd/configure.go, examples/xai-example.yaml, utils/models/provider.go, utils/models/xai.go, utils/processor/dsl.go
Enhancement
___
- Added support for X.AI as a new provider in the system.
- Integrated the Grok model under the X.AI provider.
- Updated the configuration command to include X.AI as a provider option.
- Implemented a new XAIProvider class to handle X.AI models.
- Updated the README to reflect the addition of X.AI support.
- Added an example YAML file demonstrating the use of X.AI's Grok model.
___
- `cmd/configure.go`: Added "xai" as a valid provider option in the configuration command. Included specific handling for model names starting with "grok-" for the X.AI provider.
- `utils/models/provider.go`: Added NewXAIProvider to the list of providers in the defaultDetectProvider function, allowing detection of models prefixed with "grok-".
- …
=> feat: support xai as provider

cmd/configure.go
Enhancement
___
- Introduced functions to fetch and list models from various providers (OpenAI, Anthropic, X.AI, Ollama).
- Implemented a user-friendly prompt for selecting models and configuring modes.
- Enhanced the onboarding experience by validating model names and API keys for different providers.
- Added support for parsing model selection input with ranges and removing duplicates.
- Improved error handling and user feedback during model configuration.
___
- `cmd/configure.go`: - Added imports for context, encoding/json, io, and net/http to support API interactions.
- Introduced new functions to fetch models from OpenAI, Anthropic, X.AI, and Ollama.
- Implemented `parseModelSelection` to handle user input for model selection, supporting ranges and …
=> feat: better config model seelction

examples/input.xml, examples/output.xml, examples/xml-example.yaml, utils/input/validator.go
Enhancement
___
- Added support for XML file extension in the input validator.
- Introduced example XML input and output files to demonstrate XML processing.
- Created a YAML example configuration for processing XML files.
___
- `utils/input/validator.go`: Added ".xml" to the list of supported file extensions for input validation.
- `examples/input.xml`: Created a new XML file containing sample customer data with nested elements for orders.
- `examples/output.xml`: Added a description of how to extract customer names from the XML data, listing the names found in the example input.
- `examples/xml-example.yaml`: Created a new YAML configuration file demonstrating how to process the XML input file to extract customer names using a specified model. …
=> feat: support xml

examples/google-xml-example.yaml, utils/input/handler.go, utils/processor/action_handler.go
Enhancement
___
- Added a new `MimeType` field to the `Input` struct for better MIME type handling.
- Implemented a `getMimeType` function in `handler.go` to determine the MIME type based on file extension.
- Updated `processFile`, `processImage`, and `processScreenshot` methods to set the MIME type for inputs.
- Removed duplicate `getMimeType` function from `action_handler.go` and used the `MimeType` from the input handler.
- Added an example YAML file for processing XML files with Google's Gemini model.
___
- `utils/input/handler.go`: Added a `MimeType` field to the `Input` struct. Implemented a `getMimeType` function to determine MIME types based on file extensions. Updated `processFile`, `processImage`, and `processScreenshot` methods to set the …
=> fix: mime handling for file upload

utils/processor/dsl.go, utils/processor/spinner.go
Enhancement
___
- Introduced a status spinner to improve status reporting during execution.
- Added the ability to disable the spinner in test environments.
- Integrated spinner functionality into the DSL processing workflow.
___
- `utils/processor/dsl.go`: - Added a `spinner` field to the `Processor` struct.
- Introduced the `isTestMode` function to check if the code is running in test mode.
- Modified the `NewProcessor` function to initialize the spinner and disable it in test mode.
- Integrated spinner start and stop calls at various stages of the `Process` function to provide real-time status updates.
- `utils/processor/spinner.go`: - Created a new `Spinner` struct to manage spinner behavior, including fields for characters, message, and control …
=> feat: status spinner

README.md, examples/xai-pdf-example.yaml, utils/models/xai.go
Enhancement
___
- Introduced file processing capabilities in the XAIProvider, specifically handling image files differently from other file types.
- Updated the README to reflect new capabilities of the 'grok-beta' model in the XAI section.
- Added a new example YAML file demonstrating how to process a PDF file using the 'grok-beta' model.
___
- `utils/models/xai.go`: Enhanced the `SendPromptWithFile` function to handle image files by encoding them in base64 and sending them as part of a multi-content message to the X.AI API. Introduced a context with timeout for API requests and improved error handling for API responses.
- `README.md`: Updated the 'grok-beta' model under the XAI section to indicate support for both text and file modes, reflecting the …
=> feat: xai file processing

README.md, examples/markdown-action-example.yaml, examples/test-action.md, utils/processor/action_handler.go
Enhancement
___
- Added support for using markdown files as actions in the workflow processing.
- Updated the README to include documentation on the new markdown file support.
- Added an example YAML file demonstrating the use of markdown files as actions.
- Included a sample markdown file to illustrate how actions can be stored and reused.
___
- `utils/processor/action_handler.go`: Added logic to check if an action is a markdown file. If so, the file is read, and its content is used as the action. This allows actions to be stored in markdown files for better organization and reuse.
- `README.md`: Updated the documentation to include information about the new markdown file support for actions. Added a new example demonstrating how to use markdown files …
=> feat: markdown files for actions

README.md, cmd/configure.go, examples/README.md, examples/database-connections/postgres/Dockerfile, examples/database-connections/postgres/db-example.yaml, examples/database-connections/postgres/simpledb.sql, examples/examples_test.go, examples/model-examples/variable-example.yaml, go.mod, go.sum, utils/config/env.go, utils/database/handler.go, utils/input/validator.go, utils/processor/action_handler.go, utils/processor/database_handler.go, utils/processor/dsl.go, utils/processor/model_handler.go
Enhancement
___
- Introduced PostgreSQL database connectivity for input/output operations.
- Implemented database configuration and connection testing.
- Added support for database read/write operations in the DSL.
- Enhanced the processor to handle database inputs and outputs.
- Updated the README with database integration details.
- Provided examples for database operations using Docker.
___
- `cmd/configure.go`: Added database configuration functionality, including prompts for database details and connection testing. Introduced a new flag for database configuration.
- `utils/config/env.go`: Introduced DatabaseConfig and DatabaseType structs for handling database configurations. Added methods to manage database configurations within EnvConfig.
- …
=> Database (postgres) support for input/output

examples/document-processing/markdown-action-example.yaml, examples/file-processing/analyze-csv.yaml, examples/file-processing/compare-two.yaml, examples/model-examples/model-bakeoff.yaml, utils/fileutil/fileutil.go, utils/input/handler.go, utils/models/anthropic.go, utils/models/google.go, utils/models/ollama.go, utils/models/openai.go, utils/models/xai.go, utils/processor/action_handler.go, utils/server/handlers.go, utils/server/server.go
Enhancement
___
- Refactored the `processActions` function to handle multiple file inputs more effectively.
- Removed unnecessary variable `finalResponse` and streamlined the return logic.
- Improved handling of different input types by separating file inputs and non-file inputs.
- Updated examples to reflect changes in file processing logic.
___
- `utils/processor/action_handler.go`: Refactored the `processActions` method to better handle multiple file inputs by separating file and non-file inputs. Removed the `finalResponse` variable and streamlined the return logic for different input types. Improved handling of markdown files and web scrape inputs.
- `examples/document-processing/markdown-action-example.yaml`: Updated the input path for the test CSV …
=> fix: resolve handler issue with multi file

cmd/configure.go, cmd/process.go, examples/model-examples/google-example.yaml, examples/model-examples/openai-example.yaml, utils/models/google.go, utils/models/openai.go, utils/models/provider.go
Enhancement
___
- Added support for new OpenAI models, including the "4o" and "o1" series.
- Updated Google model support to include "gemini-2.0-flash-exp".
- Refactored OpenAI model configuration to handle new model series with fixed parameters.
- Improved YAML parsing in the process command to preserve order.
- Updated example YAML files to use new model identifiers.
___
- `cmd/configure.go`: Simplified the fetching of OpenAI models by removing filtering and sorting logic. Now returns all models directly.
- `cmd/process.go`: Refactored YAML parsing to use yaml.Node for preserving order and updated the conversion logic to handle YAML nodes directly.
- `utils/models/google.go`: Added "gemini-2.0-flash-exp" to the list of valid Google models.
- …
=> New models

README.md, cmd/server.go, utils/config/env.go, utils/server/server.go, utils/server/types.go
Enhancement
___
- Introduced CORS (Cross-Origin Resource Sharing) support to the server.
- Added interactive configuration for CORS settings.
- Updated server configuration to include CORS options.
- Implemented middleware to handle CORS headers for HTTP requests.
- Updated README with instructions for configuring CORS.
___
- `cmd/server.go`: Added CORS configuration display in the server's configuration output. Introduced a new command `cors` for configuring CORS settings interactively. Implemented the `configureCORS` function to handle CORS settings input from the user.
- `utils/config/env.go`: Added a new `CORSConfig` struct to represent CORS configuration options. Updated `ServerConfig` to include a `CORS` field. Modified `GetServerConfig` to …
=> feat:  cors support

cmd/configure.go, examples/model-examples/advanced-model-comparison.yaml, examples/model-examples/deepseek-example.yaml, utils/models/deepseek.go
- support the deepseek reasoning model
=> feat: support deepseek-reasoner

examples/examples_test.go
Enhancement
___
- Updated the input validation logic in tests to allow the 'input' field to be a mapping node, in addition to scalar and sequence nodes.
- Added specific validation for web scraping inputs when 'input' is a mapping node, ensuring required keys like 'url' and 'scrape_config' are present.
- Improved error messages for missing or incorrect input configurations.
___
- `examples/examples_test.go`: - Modified the `validateStep` function to allow the 'input' field to be a mapping node, in addition to scalar and sequence nodes.
- Added a new function `validateWebScrapeInput` to validate web scraping inputs when 'input' is a mapping node, checking for the presence of 'url' and 'scrape_config' keys.
- Updated error messages to reflect the new …
=> Update Input Validation in Tests

cmd/process.go, docs/openapi.yaml, utils/config/env.go, utils/config/server.go, utils/processor/dsl.go, utils/processor/dsl_test.go, utils/processor/input_handler.go, utils/processor/input_test.go, utils/processor/model_test.go, utils/processor/output_handler.go, utils/processor/output_handler_test.go, utils/processor/progress.go, utils/server/auth.go, utils/server/bulk_operations_test.go, utils/server/env_handlers_test.go, utils/server/file_backup_test.go, utils/server/file_download_test.go, utils/server/file_handlers.go, utils/server/file_handlers_test.go, utils/server/file_upload_test.go, utils/server/handlers.go, utils/server/handlers_test.go, utils/server/provider_handlers_test.go, utils/server/server.go, utils/server/types.go
Enhancement
___
- Introduced Server-Sent Events (SSE) streaming for server processing.
- Enhanced server configuration handling, including making DataDir paths absolute.
- Refactored server and processor code to support new server configuration.
- Added comprehensive tests for new server functionalities.
- Updated OpenAPI documentation to reflect new SSE event types.
___
- `cmd/process.go`: Added a basic server configuration to the processor initialization, enabling server features during CLI processing.
- `utils/config/env.go`: Refactored server configuration handling by removing inline CORSConfig and ServerConfig definitions. Introduced logic to make DataDir paths absolute.
- `utils/config/server.go`: Introduced a new file to define ServerConfig and …
=> SSE streaming

cmd/configure.go, examples/model-examples/claude-3-7-example.yaml, utils/models/anthropic.go
Enhancement
___
- Added new Anthropic models: "claude-3-7-sonnet-20250219", "claude-3-7-sonnet-latest", and "claude-3-5-haiku-20241022".
- Updated model validation to include new models and added extra debug logging.
- Trimmed whitespace and converted model names to lowercase for validation.
- Added examples demonstrating the use of new models.
___
- `cmd/configure.go`: Added new Anthropic models "claude-3-7-sonnet-20250219", "claude-3-7-sonnet-latest", and "claude-3-5-haiku-20241022" to the list of available models.
- `utils/models/anthropic.go`: - Added new models to the validation list.
- Enhanced model validation by trimming whitespace and converting names to lowercase.
- Added debug logging to provide more detailed information during model …
=> feat: latest anthropic models

examples/model-examples/openai-model-comparison.yaml
- Confirmed support for OpenAI GPT 4.5
- Added an example
=> feat: Gpt4.5 example

README.md, examples/README.md, examples/file-processing/batch-processing-example.yaml, utils/models/google.go, utils/processor/action_handler.go, utils/processor/dsl.go, utils/processor/types.go
Enhancement
___
- Introduced a new batch processing mode that allows for individual file processing, enhancing error handling.
- Added error handling for encoding issues in files with invalid UTF-8 characters.
- Updated the Google provider to handle encoding errors more gracefully.
- Enhanced documentation to reflect new batch processing options.
- Added examples demonstrating the new batch processing capabilities.
___
- `utils/models/google.go`: Added error handling for encoding issues by checking for invalid UTF-8 characters in files. If such an error is detected, a specific error message is returned.
- `utils/processor/action_handler.go`: Implemented a new batch processing mode that processes files individually by default, with an option to skip …
=> feat: better batch processing

.gitignore, README.md, cmd/process.go, examples/followup_question.txt, examples/research_topic.txt, examples/responses-api/README.md, examples/responses-api/basic-example.yaml, examples/responses-api/conversation-example.yaml, examples/responses-api/function-calling-example.yaml, examples/responses-api/long-running-example.yaml, examples/responses-api/streaming-example.yaml, examples/responses-api/web-search-example.yaml, examples/user_question.txt, examples/weather_query.txt, utils/models/openai.go, utils/models/provider.go, utils/processor/dsl.go, utils/processor/output_handler.go, utils/processor/responses_handler.go, utils/processor/types.go
Enhancement
___
- Introduced support for OpenAI Responses API, enabling advanced interaction with OpenAI models.
- Added new functionality for handling responses, including streaming and error handling.
- Implemented examples demonstrating various use cases of the Responses API.
- Enhanced the processor to handle new step types and configurations.
- Updated documentation to reflect new features and usage instructions.
___
- `cmd/process.go`: Disabled server mode for CLI processing by setting `Enabled` to false in `ServerConfig`.
- `utils/models/openai.go`: Added extensive support for OpenAI Responses API, including request preparation, sending prompts, handling streaming, and extracting output text.
- `utils/models/provider.go`: Introduced …
=> Responses API support

examples/model-examples/ollama-example.yaml, utils/models/ollama.go, utils/processor/model_handler.go
Enhancement
___
- Transitioned from static to dynamic model detection for the Ollama provider.
- Implemented a local check to verify if a model tag exists in the local Ollama instance.
- Enhanced error handling and debug logging for better traceability.
- Updated example configuration to reflect changes in model handling.
___
- `utils/models/ollama.go`: The `SupportsModel` function was refactored to assume Ollama handles the model if no other provider claims it. Removed static prefix checks and added a safeguard against known prefixes of other providers. Updated debug logging to reflect these changes.
- `utils/processor/model_handler.go`: Introduced `OllamaTagsResponse` and `OllamaModelTag` types for handling Ollama's API response. Added …
=> fix: ollama model detection

README.md, cmd/process.go, docs/comanda-api.postman_collection.json, docs/openapi.yaml, docs/server-api.md, utils/config/server.go, utils/processor/dsl.go, utils/processor/dsl_test.go, utils/processor/input_handler.go, utils/processor/input_test.go, utils/processor/model_test.go, utils/processor/output_handler.go, utils/processor/output_handler_test.go, utils/processor/parallel_test.go, utils/server/file_handlers.go, utils/server/handlers.go, utils/server/handlers_test.go, utils/server/server.go
Enhancement
___
- Added support for a runtime directory to manage file operations.
- Updated server and processor logic to handle runtime directories.
- Enhanced file and directory navigation with runtime directory context.
- Improved server API to support runtime directory operations.
- Updated documentation to reflect changes in file management and API usage.
___
- `cmd/process.go`: Introduced a new command-line flag `--runtime-dir` to specify a runtime directory for file operations. Updated the `processCmd` to pass this runtime directory to the processor.
- `utils/config/server.go`: Added a new field `RuntimeDir` to the `ServerConfig` struct to store the runtime directory path.
- `utils/processor/dsl.go`: Updated the `Processor` struct to include a …
=> Runtime dir

utils/models/openai.go, utils/models/openai_test.go, utils/processor/dsl.go, utils/processor/input_handler.go, utils/processor/output_handler.go, utils/server/handlers.go
Enhancement
___
- Added support for new OpenAI model prefixes, including "o4-" and "gpt-4.1-".
- Improved handling of runtime directories, especially in server mode.
- Introduced comprehensive unit tests for model support and new model series detection.
- Refactored file path resolution logic to enhance clarity and maintainability.
- Added debug logging for better traceability of runtime directory and server configuration.
___
- `utils/models/openai.go`: Enhanced the `SupportsModel` function to include new model prefixes such as "o4-" and "gpt-4.1-". Updated the `isNewModelSeries` function to recognize these new models as part of the newer series.
- `utils/models/openai_test.go`: Added extensive unit tests for `SupportsModel` and `isNewModelSeries` …
=> feature: new openai models

cmd/configure.go, examples/model-examples/gemini-2.5-pro-example.yaml, utils/models/google.go
Enhancement
___
- Added support for the new Google Gemini 2.5 Pro Preview model.
- Updated the list of valid models to include the new model.
- Modified example configuration to demonstrate usage of the new model.
___
- `cmd/configure.go`: Added "gemini-2.5-pro-preview-03-25" to the list of Google models.
- `utils/models/google.go`: Included "gemini-2.5-pro-preview-03-25" in the list of valid models for validation.
- `examples/model-examples/gemini-2.5-pro-example.yaml`: Updated the model in the example configuration from "gemini-2.5-pro-exp-03-25" to "gemini-2.5-pro-preview-03-25".
</details>
___
- support for the google pro preview model
=> feat: support google pro preview

cmd/configure.go, examples/model-examples/gemini-2.5-pro-example.yaml, utils/models/google.go
Enhancement
___
- Added support for the new Google model `gemini-2.5-pro-preview-05-06`.
- Updated the list of available models in the configuration and validation functions.
- Modified example YAML to demonstrate usage of the new model.
___
- `cmd/configure.go`: Added "gemini-2.5-pro-preview-05-06" to the list of Google models in the `getGoogleModels` function.
- `utils/models/google.go`: Included "gemini-2.5-pro-preview-05-06" in the `ValidateModel` function to validate the new model.
- `examples/model-examples/gemini-2.5-pro-example.yaml`: Updated the model used in the example from "gemini-2.5-pro-preview-03-25" to "gemini-2.5-pro-preview-05-06".
</details>
___
- added support for gemini-2.5-pro-preview-05-06
=> feat: new google model

README.md, cmd/configure.go, docs/adding-new-model-guide.md, examples/model-examples/claude-4-models-example.yaml, utils/models/anthropic.go
Enhancement
___
- Added support for new Anthropic models: "claude-opus-4-20250514" and "claude-sonnet-4-20250514".
- Updated the model validation logic to include the new models.
- Modified the README to reflect changes in model support and installation instructions.
- Created a comprehensive guide for adding new models to COMandA.
- Added example YAML file demonstrating usage of the new models.
___
- `cmd/configure.go`: Added new models "claude-opus-4-20250514" and "claude-sonnet-4-20250514" to the list of Anthropic models.
- `utils/models/anthropic.go`: Updated the ValidateModel function to include the new models and their families in the validation logic.
- `README.md`: Updated installation instructions and provider configuration details to include …
=> feat: added claude 4.0 models

README.md
- updated the README to make it clearer what this project is all about
=> feat:  updated docs

.github/workflows/release.yml
- fix for the github actions bottle build
=> fix: gh action for the brew bottle

.github/workflows/release.yml
Enhancement
___
- Improved the versioning logic in the GitHub Actions release workflow to prevent tag conflicts.
- Introduced a loop to increment the patch version until a non-existing tag is found.
- Ensured that new tags are only created if they do not already exist in the repository.
___
- `.github/workflows/release.yml`: Enhanced the versioning logic by adding a loop that increments the patch version until a unique tag is found. This prevents conflicts with existing tags by checking if a tag already exists before creating a new one. If a tag exists, the patch version is incremented and checked again until a non-existing tag is found.
</details>
___
- avoid version confusion
=> fix: rev version for bottling

.github/workflows/release.yml
- fixed an issue with the bottle script re: bottle versions
=> fix: actions versioning

.github/workflows/release.yml
- update build and test gh sequencing
=> fix: (ci) sequencing commit logic

.github/workflows/release.yml
Bug fix
___
- Moved the update of the VERSION file to occur after pulling the latest changes from the main branch.
- Ensured that the VERSION file is updated only when not in dry-run mode.
- Improved the sequence of operations in the release workflow to prevent potential conflicts.
___
- `.github/workflows/release.yml`: The update of the VERSION file was moved to occur after pulling the latest changes from the main branch. This ensures that the file is only updated when not in dry-run mode, and helps prevent potential conflicts by aligning the sequence of operations more logically.
</details>
___
- changed sequence of version update
=> fix: (ci) update version sequence

.github/workflows/release.yml
=> fix: (ci) actions updates

README.md, cmd/process.go, examples/defer-example/README.md, examples/defer-example/defer.yaml, utils/processor/dsl.go, utils/processor/dsl_test.go, utils/processor/types.go
Enhancement
___
- Introduced support for conditional branching using deferred steps in YAML DSL.
- Implemented a custom YAML unmarshaler to handle mixed types at the root level.
- Added logic to process deferred steps based on JSON output from previous steps.
- Enhanced the processor to handle deferred step execution.
- Updated README to document the new feature with examples.
- Added tests to verify the functionality of deferred steps.
___
- `cmd/process.go`: Simplified YAML parsing by directly unmarshaling into the DSLConfig struct, removing the manual parsing logic for steps and parallel processes.
- `utils/processor/dsl.go`: Added a custom UnmarshalYAML method for DSLConfig to handle deferred steps and parallel steps. Implemented handleDeferredStep …
=> feat: branching support
